// Initial hp for each soldier type
#define FOOT_HEALTH 100
#define FOOTC_HEALTH 150
#define SNIPER_HEALTH 100
#define SNIPERC_HEALTH 120
#define PARAMEDIC_HEALTH 100
#define PARAMEDICC_HEALTH 200

#define FOOT_DAMAGE 10
#define FOOTC_DAMAGE 20
#define SNIPER_DAMAGE 50
#define SNIPERC_DAMAGE 100